export const locationGroups = [
  {
    label: 'Major Cities',
    options: [
      'Mumbai',
      'Delhi',
      'Bengaluru',
      'Hyderabad',
      'Chennai',
      'Kolkata',
      'Pune',
      'Ahmedabad',
      'Surat',
      'Jaipur',
      'Lucknow',
      'Kanpur',
      'Nagpur',
      'Indore',
      'Thane',
      'Bhopal',
      'Visakhapatnam',
      'Patna',
      'Vadodara',
      'Ghaziabad',
      'Ludhiana',
      'Agra',
      'Nashik',
      'Faridabad',
      'Meerut',
      'Rajkot',
      'Kalyan-Dombivli',
      'Vasai-Virar',
      'Varanasi',
      'Srinagar',
    ],
  },
  {
    label: 'South India',
    options: [
      'Coimbatore',
      'Madurai',
      'Tiruchirappalli',
      'Salem',
      'Tiruppur',
      'Erode',
      'Mysuru',
      'Mangaluru',
      'Hubballi-Dharwad',
      'Belagavi',
      'Udupi',
      'Kochi',
      'Thiruvananthapuram',
      'Kozhikode',
      'Kannur',
      'Vijayawada',
      'Guntur',
      'Nellore',
      'Tirupati',
      'Warangal',
      'Tirunelveli',
      'Thoothukudi',
    ],
  },
  {
    label: 'West & East India',
    options: [
      'Bhubaneswar',
      'Cuttack',
      'Rourkela',
      'Jamshedpur',
      'Ranchi',
      'Dhanbad',
      'Guwahati',
      'Silchar',
      'Dibrugarh',
      'Shillong',
      'Aizawl',
      'Imphal',
      'Kohima',
      'Gangtok',
      'Agartala',
      'Raipur',
      'Bilaspur',
      'Bhilai',
      'Jabalpur',
      'Ujjain',
      'Dehradun',
      'Haridwar',
      'Roorkee',
      'Shimla',
      'Chandigarh',
      'Jodhpur',
      'Udaipur',
      'Kota',
    ],
  },
  {
    label: 'Work Mode',
    options: ['Remote', 'Hybrid', 'Pan India', 'Onsite'],
  },
]

export const modeGroups = locationGroups.filter((group) => group.label === 'Work Mode')
export const locationOnlyGroups = locationGroups.filter((group) => group.label !== 'Work Mode')

export const skillGroups = [
  {
    label: 'Programming Languages',
    options: [
      'Java',
      'Python',
      'JavaScript',
      'TypeScript',
      'C',
      'C++',
      'C#',
      'PHP',
      'Ruby',
      'Go',
      'Rust',
      'Swift',
      'Kotlin',
      'Scala',
    ],
  },
  {
    label: 'Frontend & Web',
    options: [
      'React',
      'Angular',
      'Vue.js',
      'Next.js',
      'HTML',
      'CSS',
      'SASS',
      'Tailwind CSS',
      'Bootstrap',
      'Responsive Design',
      'UI/UX Design',
      'Accessibility',
    ],
  },
  {
    label: 'Backend & API',
    options: [
      'Node.js',
      'Express.js',
      'Spring Boot',
      'Spring Framework',
      'Hibernate',
      'REST API',
      'GraphQL',
      'Microservices',
      'ASP.NET',
      'Django',
      'Flask',
      'FastAPI',
    ],
  },
  {
    label: 'Data & Cloud',
    options: [
      'SQL',
      'MySQL',
      'PostgreSQL',
      'MongoDB',
      'Redis',
      'Oracle Database',
      'Power BI',
      'Tableau',
      'Excel',
      'AWS',
      'Azure',
      'Google Cloud Platform',
      'Docker',
      'Kubernetes',
      'Jenkins',
      'Linux',
    ],
  },
  {
    label: 'Tech Domains',
    options: [
      'Data Science',
      'Data Science & AI',
      'Artificial Intelligence',
      'Machine Learning',
      'Deep Learning',
      'DevOps',
      'Cloud Computing',
      'Cybersecurity',
      'Software Testing',
      'Automation Testing',
      'Mobile Development',
      'Android Development',
      'iOS Development',
      'Blockchain',
      'Internet of Things (IoT)',
      'Big Data',
      'Salesforce',
      'ERP',
      'CRM',
      'System Administration',
      'Network Administration',
      'IT Support',
    ],
  },
  {
    label: 'Business & Non-Tech',
    options: [
      'Leadership',
      'Communication',
      'Presentation Skills',
      'Public Speaking',
      'Negotiation',
      'Conflict Resolution',
      'Time Management',
      'Problem Solving',
      'Critical Thinking',
      'Project Management',
      'Agile',
      'Scrum',
      'Kanban',
      'Business Analysis',
      'Digital Marketing',
      'SEO',
      'SEM',
      'Social Media Marketing',
      'Content Writing',
      'Copywriting',
      'Sales',
      'Customer Service',
      'Finance',
      'Accounting',
      'Human Resources',
      'Recruitment',
    ],
  },
]

export const allLocationOptions = locationGroups.flatMap((group) => group.options)
export const allSkillOptions = skillGroups.flatMap((group) => group.options)
export const allModeOptions = modeGroups.flatMap((group) => group.options)

export const trainingCategoryOptions = [
  'Software Development',
  'Data Science & AI',
  'Cloud & DevOps',
  'Cybersecurity',
  'Leadership & Management',
  'Digital Transformation',
  'Design & UX',
  'Sales & Customer Success',
  'Product & Strategy',
  'Project Management',
  'Quality Assurance',
  'Business Analysis',
  'HR & Talent Development',
  'Finance & Accounting',
  'Operations',
  'Marketing',
  'Customer Support',
  'Other',
]
