spring.application.name=trainerpro

server.port=8090


# DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/trainerpro_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# CORS
app.cors.allowed-origin=http://localhost:5173,http://localhost:5174